import express, { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { db } from './db-supabase';
import { User, OrderStatus, PaymentStatus } from '../src/types';

const router = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || 'joy-and-ride-laundry-secure-secret-key-eldoret';

export interface AuthRequest extends Request { user?: User; }

export function authenticateToken(req: AuthRequest, res: Response, next: NextFunction) {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];
  if (!token) return res.status(401).json({success:false,error:{code:'UNAUTHORIZED',message:'Authentication required'}});
  try {
    const decoded = jwt.verify(token, JWT_SECRET) as { id:string; email:string; role:string };
    const user = db.findUserById(decoded.id);
    if (!user) return res.status(401).json({success:false,error:{code:'USER_NOT_FOUND',message:'User account no longer exists'}});
    const {passwordHash:_,...safeUser}=user; req.user=safeUser; next();
  } catch { return res.status(403).json({success:false,error:{code:'INVALID_TOKEN',message:'Invalid or expired session token'}}); }
}
export function requireAdmin(req: AuthRequest,res:Response,next:NextFunction){ authenticateToken(req,res,()=>{ if(req.user?.role!=='admin') return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Administrator privileges required'}}); next(); }); }
export function optionalAuth(req:AuthRequest,_res:Response,next:NextFunction){const authHeader=req.headers['authorization'];const token=authHeader&&authHeader.split(' ')[1];if(token){try{const decoded=jwt.verify(token,JWT_SECRET) as {id:string};const user=db.findUserById(decoded.id);if(user){const {passwordHash:_,...safeUser}=user;req.user=safeUser;}}catch{}}next();}
function generateToken(user:User){return jwt.sign({id:user.id,email:user.email,role:user.role,fullName:user.fullName},JWT_SECRET,{expiresIn:'7d'});}

router.post('/auth/register',(req,res)=>{try{const{fullName,email,phone,password,address,area}=req.body;if(!fullName||!email||!phone||!password)return res.status(400).json({success:false,error:{code:'MISSING_FIELDS',message:'Full name, email, phone number, and password are required'}});if(password.length<6)return res.status(400).json({success:false,error:{code:'WEAK_PASSWORD',message:'Password must be at least 6 characters'}});if(db.findUserByEmail(email))return res.status(409).json({success:false,error:{code:'EMAIL_EXISTS',message:'An account with this email already exists. Please log in.'}});const user=db.createUser({fullName,email,phone,password,role:'customer',address,area});return res.status(201).json({success:true,data:{user,token:generateToken(user)},message:'Account created successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message||'Registration failed'}});}});
router.post('/auth/login',(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({success:false,error:{code:'MISSING_CREDENTIALS',message:'Email and password are required'}});const rawUser=db.findUserByEmail(email);if(!rawUser)return res.status(401).json({success:false,error:{code:'INVALID_CREDENTIALS',message:'Invalid email or password'}});if(!bcrypt.compareSync(password,rawUser.passwordHash))return res.status(401).json({success:false,error:{code:'INVALID_CREDENTIALS',message:'Invalid email or password'}});const{passwordHash:_,...safeUser}=rawUser;return res.json({success:true,data:{user:safeUser,token:generateToken(safeUser)}});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message||'Login failed'}});}});
router.post('/auth/admin-login',(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({success:false,error:{code:'MISSING_CREDENTIALS',message:'Admin email and password are required'}});const rawUser=db.findUserByEmail(email);if(!rawUser)return res.status(401).json({success:false,error:{code:'UNAUTHORIZED_ADMIN',message:'Invalid administrative credentials'}});if(rawUser.role!=='admin')return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'This account does not have administrative privileges'}});if(!bcrypt.compareSync(password,rawUser.passwordHash))return res.status(401).json({success:false,error:{code:'UNAUTHORIZED_ADMIN',message:'Invalid administrative credentials'}});const{passwordHash:_,...safeUser}=rawUser;db.addAuditLog(safeUser.email,'admin','ADMIN_LOGIN','auth',safeUser.id,'Administrator logged in successfully');return res.json({success:true,data:{user:safeUser,token:generateToken(safeUser)}});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message||'Admin login failed'}});}});
router.get('/auth/me',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:{user:req.user}}));
router.put('/auth/profile',authenticateToken,(req:AuthRequest,res)=>{try{const{fullName,phone,address,area}=req.body;const updated=db.updateUserProfile(req.user!.id,{fullName,phone,address,area});return res.json({success:true,data:{user:updated},message:'Profile updated successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});

router.get('/services',(_req,res)=>res.json({success:true,data:db.getServices(true)}));
router.get('/admin/services',requireAdmin,(_req,res)=>res.json({success:true,data:db.getServices(false)}));
router.post('/admin/services',requireAdmin,(req:AuthRequest,res)=>{try{const{name,description,category,priceType,basePrice,unit,image,active,turnaroundHours,tags,popular}=req.body;if(!name||!category||basePrice===undefined||!unit)return res.status(400).json({success:false,error:{code:'INVALID_DATA',message:'Service name, category, unit, and base price are required'}});const service=db.createService({name,description:description||'',category,priceType:priceType||'per_item',basePrice:Number(basePrice),unit,image:image||INITIAL_IMAGE,active:active!==undefined?active:true,turnaroundHours:Number(turnaroundHours)||24,popular:Boolean(popular),tags:Array.isArray(tags)?tags:[]},req.user!.email);return res.status(201).json({success:true,data:service,message:'Service added successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.put('/admin/services/:id',requireAdmin,(req:AuthRequest,res)=>{try{const updated=db.updateService(req.params.id,req.body,req.user!.email);if(!updated)return res.status(404).json({success:false,error:{code:'SERVICE_NOT_FOUND',message:'Service does not exist'}});return res.json({success:true,data:updated,message:'Service updated successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.delete('/admin/services/:id',requireAdmin,(req:AuthRequest,res)=>{try{const deleted=db.deleteService(req.params.id,req.user!.email);if(!deleted)return res.status(404).json({success:false,error:{code:'SERVICE_NOT_FOUND',message:'Service does not exist'}});return res.json({success:true,message:'Service removed successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});

router.post('/orders',optionalAuth,(req:AuthRequest,res)=>{try{const{customerName,customerPhone,customerEmail,pickupOption,pickupAddress,pickupArea,pickupDate,pickupTimeSlot,deliveryOption,deliveryAddress,deliveryArea,deliveryDate,deliveryTimeSlot,items,paymentMethod,customerNotes}=req.body;if(!customerName||!customerPhone||!items||!items.length)return res.status(400).json({success:false,error:{code:'INVALID_ORDER',message:'Name, phone number, and at least one laundry item are required'}});let customerId=req.user?.id;const finalEmail=(customerEmail||req.user?.email||`customer-${customerPhone.replace(/\D/g,'')}@joyridelaundry.co.ke`).toLowerCase();if(!customerId){let existing=db.findUserByEmail(finalEmail);if(!existing){const guest=db.createUser({fullName:customerName,email:finalEmail,phone:customerPhone,password:'GuestUser'+Math.random().toString(36).slice(2,8),role:'customer',address:pickupAddress||deliveryAddress||'',area:pickupArea||deliveryArea||'Hawai Road & Environs'});customerId=guest.id;}else customerId=existing.id;}const order=db.createOrder({customerId,customerName,customerPhone,customerEmail:finalEmail,pickupOption:pickupOption||'doorstep_pickup',pickupAddress:pickupAddress||'Hawai Road, Eldoret',pickupArea:pickupArea||'Hawai Road & Environs',pickupDate:pickupDate||new Date().toISOString().slice(0,10),pickupTimeSlot:pickupTimeSlot||'08:00 AM - 11:00 AM',deliveryOption:deliveryOption||'doorstep_delivery',deliveryAddress:deliveryAddress||pickupAddress||'Hawai Road, Eldoret',deliveryArea:deliveryArea||pickupArea||'Hawai Road & Environs',deliveryDate:deliveryDate||new Date(Date.now()+172800000).toISOString().slice(0,10),deliveryTimeSlot:deliveryTimeSlot||'02:00 PM - 05:00 PM',items,paymentMethod:paymentMethod||'pay_on_delivery',customerNotes});return res.status(201).json({success:true,data:order,message:'Laundry order created successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.get('/orders',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:db.getOrders({customerId:req.user!.id})}));
router.get('/orders/:id',optionalAuth,(req:AuthRequest,res)=>{const order=db.getOrderById(req.params.id);if(!order)return res.status(404).json({success:false,error:{code:'ORDER_NOT_FOUND',message:'Order not found'}});if(req.user?.role!=='admin'&&order.customerId!==req.user?.id)return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'You do not have access to this order'}});return res.json({success:true,data:order});});
router.get('/admin/orders',requireAdmin,(req,res)=>res.json({success:true,data:db.getOrders({status:req.query.status as OrderStatus,search:req.query.search as string})}));
router.patch('/admin/orders/:id/status',requireAdmin,(req:AuthRequest,res)=>{try{const updated=db.updateOrderStatus(req.params.id,req.body.status,req.user!.email,req.body.note,req.body.paymentStatus);if(!updated)return res.status(404).json({success:false,error:{code:'ORDER_NOT_FOUND',message:'Order not found'}});return res.json({success:true,data:updated,message:'Order status updated successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.patch('/admin/orders/:id',requireAdmin,(req:AuthRequest,res)=>{try{const updated=db.updateOrderDetails(req.params.id,req.body,req.user!.email);if(!updated)return res.status(404).json({success:false,error:{code:'ORDER_NOT_FOUND',message:'Order not found'}});return res.json({success:true,data:updated,message:'Order updated successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});

router.get('/bookings',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:db.getBookings(req.user!.role==='admin'?undefined:req.user!.id)}));
router.post('/bookings',authenticateToken,(req:AuthRequest,res)=>{try{const booking=db.createBooking({...req.body,customerId:req.user!.id,customerEmail:req.user!.email});return res.status(201).json({success:true,data:booking,message:'Booking created successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.patch('/admin/bookings/:id/status',requireAdmin,(req:AuthRequest,res)=>{const updated=db.updateBookingStatus(req.params.id,req.body.status,req.user!.email);if(!updated)return res.status(404).json({success:false,error:{code:'BOOKING_NOT_FOUND',message:'Booking not found'}});return res.json({success:true,data:updated});});

router.get('/admin/deliveries',requireAdmin,(_req,res)=>res.json({success:true,data:db.getDeliveries()}));
router.patch('/admin/deliveries/:id',requireAdmin,(req:AuthRequest,res)=>{const updated=db.updateDeliveryStatus(req.params.id,req.body,req.user!.email);if(!updated)return res.status(404).json({success:false,error:{code:'DELIVERY_NOT_FOUND',message:'Delivery not found'}});return res.json({success:true,data:updated});});

router.get('/notifications',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:db.getNotifications(req.user!.id)}));
router.patch('/notifications/:id/read',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:db.markNotificationAsRead(req.params.id,req.user!.id)}));
router.patch('/notifications/read-all',authenticateToken,(req:AuthRequest,res)=>res.json({success:true,data:db.markAllNotificationsAsRead(req.user!.id)}));

router.get('/admin/settings',requireAdmin,(_req,res)=>res.json({success:true,data:db.getSettings()}));
router.put('/admin/settings',requireAdmin,(req:AuthRequest,res)=>{try{return res.json({success:true,data:db.updateSettings(req.body,req.user!.email),message:'Business settings updated successfully'});}catch(err:any){return res.status(500).json({success:false,error:{code:'SERVER_ERROR',message:err.message}});}});
router.get('/admin/metrics',requireAdmin,(_req,res)=>res.json({success:true,data:db.getAdminMetrics()}));
router.get('/admin/audit-logs',requireAdmin,(_req,res)=>res.json({success:true,data:db.getAuditLogs()}));

router.get('/events',authenticateToken,(req:AuthRequest,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders?.();const unsubscribe=db.subscribeSSE((event,data)=>{res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);});req.on('close',unsubscribe);res.write(`event: CONNECTED\ndata: ${JSON.stringify({time:new Date().toISOString()})}\n\n`);});

const INITIAL_IMAGE='https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=800&q=80';
export default router;
